"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { ThemeProvider } from 'next-themes'
import { SessionProvider } from 'next-auth/react'
import Background from '@/components/Background'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <ThemeProvider enableSystem={true} attribute='class' defaultTheme='system'>
            <Navbar/>
            <Background/>
            {children}
            <Footer/>
          </ThemeProvider>
        </SessionProvider>
        </body>
    </html>
  )
}
